=== IshaanBose2147116/lab-program-01/xml/driver-data.xsd
<?xml version="1.0"?>
<sb:schema xmlns:sb="http://www.w3.org/2001/XMLSchema">
<sb:element name="drivers" type="root" />

<sb:complexType name="root">
    <sb:sequence>
        <sb:element name="driver" type="driverElement" />
    </sb:sequence>
</sb:complexType>

<sb:complexType name="driverElement">
    <sb:sequence>
        <sb:element name="name" type="sb:string" />
        <sb:element name="dob" type="sb:string" />
        <sb:element name="vehicle-assigned" type="sb:string" />
        <sb:element name="license-type">
            <sb:simpleType>
                <sb:restriction base="sb:string">
                    <sb:enumeration value="Bus" />
                    <sb:enumeration value="Van" />
                    <sb:enumeration value="Bus/Van" />
                </sb:restriction>
            </sb:simpleType>
        </sb:element>
        <sb:element name="route" type="routeElement" />
    </sb:sequence>
    <sb:attribute name="emp-id" type="sb:integer" />
</sb:complexType>

<sb:complexType name="routeElement">
    <sb:sequence>
        <sb:element name="route-start" type="sb:string" />
        <sb:element name="route-end" type="sb:string" />
        <sb:element name="sched-start" type="sb:string" />
        <sb:element name="sched-end" type="sb:string" />
        <sb:element name="drop-offs" type="dropOffsElement" />
    </sb:sequence>
</sb:complexType>

<sb:complexType name="dropOffsElement">
    <sb:sequence>
        <sb:element name="drop-off" type="dropOffElement" maxOccurs="unbounded" />
    </sb:sequence>
</sb:complexType>

<sb:complexType name="dropOffElement">
    <sb:sequence>
        <sb:element name="address" type="sb:string" />
        <sb:element name="no-drop-offs">
            <sb:simpleType>
                <sb:restriction base="sb:integer">
                    <sb:minExclusive value="0" />
                </sb:restriction>
            </sb:simpleType>
        </sb:element>
    </sb:sequence>
</sb:complexType>
</sb:schema>

=== IshaanBose2147116/lab-program-01/xml/driver-data.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="./driver-data.xsl" type="text/xsl"?>
<drivers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="./driver-data.xsd">
    <driver emp-id="300150">
        <name>Santosh Roy</name>
        <dob>1992-04-19</dob>
        <vehicle-assigned>MH 11 K 8900</vehicle-assigned>
        <license-type>Bus</license-type>
        <route>
            <route-start>Route start address</route-start>
            <route-end>Route end address</route-end>
            <sched-start>06:20 am</sched-start>
            <sched-end>07:55 am</sched-end>
            <drop-offs>
                <drop-off>
                    <address>Drop off address 2</address>
                    <no-drop-offs>2</no-drop-offs>
                </drop-off>
                <drop-off>
                    <address>Drop off address 1</address>
                    <no-drop-offs>1</no-drop-offs>
                </drop-off>
                <drop-off>
                    <address>Drop off address 3</address>
                    <no-drop-offs>5</no-drop-offs>
                </drop-off>
                <drop-off>
                    <address>Drop off address 5</address>
                    <no-drop-offs>3</no-drop-offs>
                </drop-off>
                <drop-off>
                    <address>Drop off address 4</address>
                    <no-drop-offs>1</no-drop-offs>
                </drop-off>
            </drop-offs>
        </route>
    </driver>
</drivers>
